// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: 'ts-node --compiler-options "{\\"module\\":\\"CommonJS\\"}" prisma/seed.ts',
  },
  datasource: {
    // Use the Supabase *direct* (non-pooled, port 5432) connection string here —
    // migrations don't work reliably through the pgbouncer pooled connection.
    url: process.env["DATABASE_URL"],
  },
});
